FROM python:3.11-slim

# Install common data/plotting libs
RUN pip install matplotlib seaborn pandas numpy

# Set working directory
WORKDIR /app

# Default command (will be overridden)
CMD ["python3"]
