import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

# Data from the query
data = [
    {'Product': 'AMD Ryzen 5 5600X', 'Quantity_Sold': 10, 'Revenue': 2000},
    {'Product': 'Gigabyte B650E Aorus Master', 'Quantity_Sold': 4, 'Revenue': 800},
    {'Product': 'NVIDIA GeForce RTX 3070', 'Quantity_Sold': 2, 'Revenue': 1800}
]

df = pd.DataFrame(data)

# Create a figure with subplots
fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(15, 6))

# Set the style
plt.style.use('seaborn-v0_8')
sns.set_palette("husl")

# Chart 1: Bar chart for Quantity Sold
bars1 = ax1.bar(df['Product'], df['Quantity_Sold'], color=['#FF6B6B', '#4ECDC4', '#45B7D1'])
ax1.set_title('Top 3 Best-Selling Products by Quantity', fontsize=16, fontweight='bold')
ax1.set_ylabel('Units Sold', fontsize=12)
ax1.set_xlabel('Products', fontsize=12)

# Add value labels on bars
for bar in bars1:
    height = bar.get_height()
    ax1.text(bar.get_x() + bar.get_width()/2., height + 0.1,
             f'{int(height)}', ha='center', va='bottom', fontweight='bold')

# Rotate x-axis labels for better readability
plt.setp(ax1.get_xticklabels(), rotation=45, ha='right')

# Chart 2: Bar chart for Revenue
bars2 = ax2.bar(df['Product'], df['Revenue'], color=['#FF6B6B', '#4ECDC4', '#45B7D1'])
ax2.set_title('Revenue Generated by Top 3 Best-Selling Products', fontsize=16, fontweight='bold')
ax2.set_ylabel('Revenue ($)', fontsize=12)
ax2.set_xlabel('Products', fontsize=12)

# Add value labels on bars
for bar in bars2:
    height = bar.get_height()
    ax2.text(bar.get_x() + bar.get_width()/2., height + 50,
             f'${int(height)}', ha='center', va='bottom', fontweight='bold')

# Rotate x-axis labels for better readability
plt.setp(ax2.get_xticklabels(), rotation=45, ha='right')

# Adjust layout to prevent overlapping
plt.tight_layout()

# Save the figure
plt.savefig(r'output.png', dpi=300, bbox_inches='tight')
plt.close()

# Also create a combined chart
fig2, ax3 = plt.subplots(figsize=(12, 8))

# Create a combined bar chart with dual y-axes
x_pos = np.arange(len(df['Product']))
width = 0.35

# First axis for quantity
ax3_twin = ax3.twinx()
bars_quantity = ax3.bar(x_pos - width/2, df['Quantity_Sold'], width, 
                        label='Quantity Sold', color='#FF6B6B', alpha=0.8)
bars_revenue = ax3_twin.bar(x_pos + width/2, df['Revenue'], width, 
                           label='Revenue ($)', color='#4ECDC4', alpha=0.8)

# Customize the plot
ax3.set_title('Top 3 Best-Selling Products: Quantity vs Revenue', fontsize=16, fontweight='bold')
ax3.set_xlabel('Products', fontsize=12)
ax3.set_ylabel('Quantity Sold (units)', fontsize=12)
ax3_twin.set_ylabel('Revenue ($)', fontsize=12)
ax3.set_xticks(x_pos)
ax3.set_xticklabels(df['Product'], rotation=45, ha='right')

# Add value labels on bars
for bar in bars_quantity:
    height = bar.get_height()
    ax3.text(bar.get_x() + bar.get_width()/2., height + 0.1,
             f'{int(height)}', ha='center', va='bottom', fontweight='bold')

for bar in bars_revenue:
    height = bar.get_height()
    ax3_twin.text(bar.get_x() + bar.get_width()/2., height + 50,
                  f'${int(height)}', ha='center', va='bottom', fontweight='bold')

# Add legends
ax3.legend(loc='upper left')
ax3_twin.legend(loc='upper right')

plt.tight_layout()
plt.savefig(r'output_combined.png', dpi=300, bbox_inches='tight')
plt.close()

print("Charts created successfully!")
print("Top 3 Best-Selling Products:")
for i, row in df.iterrows():
    print(f"{i+1}. {row['Product']}: {row['Quantity_Sold']} units sold, ${row['Revenue']} revenue")