import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Create the data for the 2 most selling products
data = {
    'Product': ['AMD Ryzen 5 5600X', 'Gigabyte B650E Aorus Master'],
    'Brand': ['AMD', 'Corsair'],
    'TotalQuantitySold': [10, 4],
    'TotalRevenue': [2000, 800]
}

df = pd.DataFrame(data)

# Create the visualization
fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(15, 6))

# Chart 1: Quantity Sold
bars1 = ax1.bar(df['Product'], df['TotalQuantitySold'], color=['#FF6B6B', '#4ECDC4'])
ax1.set_title('2 Most Selling Products by Quantity', fontsize=16, fontweight='bold')
ax1.set_ylabel('Units Sold', fontsize=12)
ax1.set_xlabel('Product Name', fontsize=12)
ax1.set_xticklabels(df['Product'], rotation=45, ha='right')

# Add value labels on bars
for bar in bars1:
    height = bar.get_height()
    ax1.text(bar.get_x() + bar.get_width()/2., height + 0.1,
             f'{int(height)}', ha='center', va='bottom', fontweight='bold')

# Chart 2: Total Revenue
bars2 = ax2.bar(df['Product'], df['TotalRevenue'], color=['#45B7D1', '#96CEB4'])
ax2.set_title('Total Revenue Generated by Top 2 Products', fontsize=16, fontweight='bold')
ax2.set_ylabel('Revenue ($)', fontsize=12)
ax2.set_xlabel('Product Name', fontsize=12)
ax2.set_xticklabels(df['Product'], rotation=45, ha='right')

# Add value labels on bars
for bar in bars2:
    height = bar.get_height()
    ax2.text(bar.get_x() + bar.get_width()/2., height + 20,
             f'${int(height)}', ha='center', va='bottom', fontweight='bold')

# Add brand information as annotations
for i, (product, brand) in enumerate(zip(df['Product'], df['Brand'])):
    ax1.text(i, -1.5, f'Brand: {brand}', ha='center', fontsize=10, 
             bbox=dict(boxstyle="round,pad=0.3", facecolor='lightgray', alpha=0.7))
    ax2.text(i, -80, f'Brand: {brand}', ha='center', fontsize=10,
             bbox=dict(boxstyle="round,pad=0.3", facecolor='lightgray', alpha=0.7))

plt.tight_layout()
plt.savefig(r"output.png", dpi=300, bbox_inches='tight')
plt.close()

print("Chart created successfully showing:")
print(f"1. AMD Ryzen 5 5600X: 10 units sold, $2,000 total revenue")
print(f"2. Gigabyte B650E Aorus Master: 4 units sold, $800 total revenue")